<ChangePasswordScreen>:
    FloatLayout:
        BoxLayout:
            orientation: 'vertical'
            size_hint: 1, 0.8
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            Label:
                text: 'Change Password'
                font_size: '24sp'

            TextInput:
                id: username
                hint_text: 'Username'
                multiline: False
                size_hint_y: None
                height: '50dp'

            TextInput:
                id: current_password
                hint_text: 'Current Password'
                password: True
                multiline: False
                size_hint_y: None
                height: '50dp'

            TextInput:
                id: new_password
                hint_text: 'New Password'
                password: True
                multiline: False
                size_hint_y: None
                height: '50dp'

            TextInput:
                id: confirm_new_password
                hint_text: 'Confirm New Password'
                password: True
                multiline: False
                size_hint_y: None
                height: '50dp'

            Button:
                text: 'Change Password'
                size_hint_y: None
                height: '50dp'
                on_release: root.submit_password_change()

            Button:
                text: 'Back to login'
                size_hint_y: None
                height: '50dp'
                on_press: app.root.current = "login"

