<Post>:
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size
    orientation: 'vertical'
    Image:
        source: root.profilePicture
        size_hint: None, None
        size: 50, 50
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Ellipse:
                pos: self.pos
                size: self.size
    Label:
        text: root.username
    Label:
        text: root.message
        text_size: self.width, None
        size_hint: 1, None
        height: self.texture_size[1]

<Posts>:
    size_hint: 0.9, 0.6
    pos_hint: {'center_x': 0.5, 'center_y': 0.55}
    viewclass: "Post"
    RecycleBoxLayout:
        padding: 10
        spacing: 10
        default_size_hint: 1, None
        size_hint_y: None
        height: self.minimum_height
        orientation: "vertical"