<RegisterScreen>:
    FloatLayout:
        BoxLayout:
            orientation: 'vertical'
            size_hint: 0.8, 0.5
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            Label:
                text: 'Register Screen'
                font_size: '24sp'

            TextInput:
                id: unique_code
                hint_text: 'Unique Code'
                multiline: False
                size_hint_y: None
                height: '50dp'

            TextInput:
                id: username
                hint_text: 'Username'
                multiline: False
                size_hint_y: None
                height: '50dp'

            TextInput:
                id: password
                hint_text: 'Password'
                password: True
                multiline: False
                size_hint_y: None
                height: '50dp'

            TextInput:
                id: confirm_password
                hint_text: 'Confirm Password'
                password: True
                multiline: False
                size_hint_y: None
                height: '50dp'

            Button:
                text: 'Register'
                size_hint_y: None
                height: '50dp'
                on_release: root.validate_register()

            Label:
                id: register_message
                color: (1, 0, 0, 1)
                size_hint_y: None
                height: '30dp'
