<SchoolAssignmentsScreen@BaseScreen>:

    #back arrow
    Button:
        on_release: app.root.current = 'school'
        background_normal: 'Assets/BackArrow.png'
        size_hint: None, None
        size: 50, 50
        pos_hint: {'right': 0.10, 'top': 0.95}
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Ellipse:
                pos: self.pos
                size: self.size

    FloatLayout:
        ScrollView:
            size_hint: (0.8, 0.6)
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}

            BoxLayout:
                id: assignment_layout
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: 30
                padding: 5


        Button:
            pos_hint: {'center_x' : 0.5, 'center_y' : 0.14}
            size_hint: 0.9, 0.1
            text: 'Add Assignment'
            on_release: app.root.current = 'add_assignment'



<AddAssignmentScreen@BaseScreen>:

    #back arrow
    Button:
        on_release: app.root.current = 'school_assignments'
        background_normal: 'Assets/BackArrow.png'
        size_hint: None, None
        size: 50, 50
        pos_hint: {'right': 0.10, 'top': 0.95}
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Ellipse:
                pos: self.pos
                size: self.size

    BoxLayout:
        orientation: 'vertical'
        pos_hint: {'center_x' : 0.5, 'center_y' : 0.5}
        size_hint: 0.8, 0.5


        Label:
            text: 'Add a New Assignment'
            font_size: 30

        TextInput:
            id: assignment_title
            hint_text: 'Please enter the assignment title'

        TextInput:
            id: assignment_content
            hint_text: 'Enter assignment content'

        TextInput:
            id: assignment_deadline
            hint_text: 'Enter the deadline for the assignment in DD/MM/YYYY format please'

        TextInput:
            id: assignment_time
            hint_text: 'Enter the time that the assignment is due in hh:mm:ss format please'


        Button:
            text: 'Submit'
            on_release: root.create_assignment()



<AssignmentSubmissionScreen@BaseScreen>:

    #back arrow
    Button:
        on_release: app.root.current = 'school_assignments'
        background_normal: 'Assets/BackArrow.png'
        size_hint: None, None
        size: 50, 50
        pos_hint: {'right': 0.10, 'top': 0.95}
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Ellipse:
                pos: self.pos
                size: self.size

    BoxLayout:
        orientation: 'vertical'
        size_hint: 0.8, 0.5

        Label:
            id: assignment_submission
            text: 'Assignment Details'

        Label:
            id: assignment_title
            text: ''

        Label:
            id: assignment_content
            text: ''

        Label:
            id: assignment_deadline
            text: ''

        TextInput:
            id: submission_content
            hint_text: 'Enter work here'

        Button:
            text: 'Submit'
            on_release: root.submit_assignment()


<AssignmentGradingScreen@BaseScreen>:

    #back arrow
    Button:
        on_release: app.root.current = 'school_assignments'
        background_normal: 'Assets/BackArrow.png'
        size_hint: None, None
        size: 50, 50
        pos_hint: {'right': 0.10, 'top': 0.95}
        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            Ellipse:
                pos: self.pos
                size: self.size

    BoxLayout:
        orientation: 'vertical'
        pos_hint: {'center_x' : 0.5, 'center_y' : 0.5}
        size_hint: 0.8, 0.5

        TextInput:
            id: assignment_grade
            hint_text: 'Please enter the grade number out of 100'

        TextInput:
            id: assignment_feedback
            hint_text: 'Please enter any feedback you would like to give'

        Button:
            text: 'Submit'
            on_release: app.root.current = 'school_assignments'
